class ReadingTopicData {
  const ReadingTopicData({
    required this.id,
    required this.title,
    required this.sentences,
    required this.keyPoints,
  });

  final int id;
  final String title;
  final List<String> sentences;
  final String keyPoints;
}

const List<ReadingTopicData> readingTopics = [
  ReadingTopicData(
    id: 1,
    title: 'The first American woman in Space',
    sentences: [
      'With the support from her parents, she went to university to study science.',
      'Her degree enabled her to get a place on the training course in USA.',
      'This is about space, and it helps Mae to become a member of a research team.',
      'As part of this group, she traveled to space and did a lot of experiments.',
      'Some of those were about growing plants and some animals in a spaceship.',
    ],
    keyPoints: 'Parents support → degree → USA training → research team → space experiments with plants and animals',
  ),
  ReadingTopicData(
    id: 2,
    title: 'Music show at the park',
    sentences: [
      'The local authority planned, sponsored, and paid for everything.',
      'Because of this, it was free and 5000 people attended it.',
      'Many of them arrived early and visited nearby shops while they were waiting for it to begin.',
      'The staff there had a busy day, but they were able to close early and watch the famous singer perform.',
      'He performed for two hours and everyone had great fun.',
    ],
    keyPoints: 'Government funding → free event → 5000 people → early arrival & shopping → staff enjoyed show → 2 hours performance',
  ),
  ReadingTopicData(
    id: 3,
    title: 'Café (The first day)',
    sentences: [
      'It was crowded, and the staff were very busy on their first day of working.',
      'Luckily, they still found me a table and gave me the menu.',
      'I was disappointed when looking at the menu because there were few dishes.',
      'I chose the most expensive food, and decided to order a sandwich.',
      'It tasted quite good with cheese topping, so I will definitely come back again!',
    ],
    keyPoints: 'Crowded first day → found table → few menu items → ordered expensive sandwich → delicious with cheese → will return',
  ),
  ReadingTopicData(
    id: 4,
    title: 'Making Films / Movies',
    sentences: [
      'The films in that period were different from the films of today.',
      'This is because they were black and white, and there was no sound.',
      'In addition to these technical limitations, film producers also had a very low budget.',
      'This lack of money mostly affected actors, and they didn\'t earn much.',
      'Things have changed over time, and some of them have earned millions of dollars after appearing in films.',
    ],
    keyPoints: 'Old films: black & white, no sound → low budget → poor actors → Modern: big earnings from films',
  ),
  ReadingTopicData(
    id: 5,
    title: 'Weekend Activities',
    sentences: [
      'It started early on Saturday morning with a ten-mile race for adults.',
      '60 men and women ran in this, and Ms Kamur won with a very fast time.',
      'After receiving the prize, the children\'s activities and competitions began.',
      'These activities included football, jumping, and swimming, and they had lots of fun.',
      'They were all very hungry after all these, so they enjoyed tasty food and drinks with their parents.',
    ],
    keyPoints: 'Adult 10-mile race → Ms Kamur wins → children\'s activities (football, jumping, swimming) → food & drinks with parents',
  ),
  ReadingTopicData(
    id: 6,
    title: 'The history of travel',
    sentences: [
      'In the past, only very rich people could afford to travel long distances.',
      'The invention of cars and trains had changed everything and made travelling cheaper.',
      'After these vehicles, travelling becomes even easier with aeroplanes.',
      'Because flying with them is so fast, more people now go abroad for holiday.',
      'It is more convenient to travel to other part of the world due to the improvement in transports.',
    ],
    keyPoints: 'Past: only rich travel → cars & trains cheaper → airplanes easier → fast flying → more foreign holidays → convenient travel',
  ),
  ReadingTopicData(
    id: 7,
    title: 'Singer',
    sentences: [
      'Before becoming famous at a young age, he studied art and music at high school.',
      'During this education, he started to perform on stage.',
      'During his stage performances, he wore colorful clothes and painted his face.',
      'This strange ways of dressing and his songs attracted people\'s attention.',
      'They started to follow him on social media and he is now very famous.',
    ],
    keyPoints: 'High school art & music → stage performances → colorful clothes & face paint → attracted attention → social media followers → famous',
  ),
  ReadingTopicData(
    id: 8,
    title: 'Healthy Eating',
    sentences: [
      'In the past, meals were often high in sugar and unhealthy fats.',
      'Limited access to fresh produce made healthy eating harder years ago.',
      'Modern diets emphasize fresh, whole foods over processed options.',
      'Nutritionists now educate people on balanced meal planning.',
      'Today, apps help track calories and suggest healthy recipes.',
    ],
    keyPoints: 'Past: high sugar & unhealthy fats → limited fresh produce → Modern: fresh whole foods → nutritionist education → calorie tracking apps',
  ),
  ReadingTopicData(
    id: 9,
    title: 'Neighborhood Festival',
    sentences: [
      'The festival was held on Friday evening, featuring live music performances.',
      'Around 100 people attended, with Ms. Carter leading the organizing team.',
      'After the performances, awards were given for the best food stall.',
      'Activities included dance workshops, art displays, and a pet parade.',
      'Families stayed late, enjoying food and drinks under colorful lights.',
    ],
    keyPoints: 'Friday evening live music → 100 people → Ms. Carter organized → awards for food → dance workshops & pet parade → colorful lights',
  ),
  ReadingTopicData(
    id: 10,
    title: 'Public Transportation',
    sentences: [
      'City buses today are more efficient than those from a decade ago.',
      'Older buses often lacked air conditioning and comfortable seats.',
      'Due to budget limitations, many cities had fewer bus routes in the past.',
      'Drivers and staff now receive better training to assist passengers.',
      'Modern buses often use electric power, reducing pollution in urban areas.',
    ],
    keyPoints: 'Modern buses: efficient → old buses: no AC & poor seats → past: few routes → today: better training → electric power reduces pollution',
  ),
  ReadingTopicData(
    id: 11,
    title: 'Artificial intelligence',
    sentences: [
      'Over the past decade, artificial intelligence has revolutionized various industries.',
      'The early AI systems were limited to simple pattern recognition tasks.',
      'High computational costs previously hindered the development of AI.',
      'Nowadays, AI engineers build advanced models for complex tasks.',
      'Modern AI tools help businesses to analyze data and make better decisions.',
    ],
    keyPoints: 'AI revolutionized industries → early systems: limited pattern recognition → high costs hindered → modern: advanced models → business data analysis',
  ),
  ReadingTopicData(
    id: 12,
    title: 'Writing about a place',
    sentences: [
      'Before writing about a place, you need to do some research on it.',
      'It is important to learn about the people and the history there carefully.',
      'Even if you can not visit the place, your writing will look similar to real experiences.',
      'You should also compare that place with your own country.',
      'Such comparisons will make your writing more interesting and meaningful.',
    ],
    keyPoints: 'Research first → learn people & history → write like real experience → compare with own country → more interesting writing',
  ),
  ReadingTopicData(
    id: 13,
    title: 'Workplace evolution',
    sentences: [
      'Flexible work models are becoming more common in modern workplaces.',
      'Previously, employees were confined to rigid nine-to-five work hours.',
      'Technological restrictions once made remote work a challenge.',
      'Today, businesses are exploring shorter workweeks to boost productivity.',
      'Managers now utilize software to monitor project progress remotely.',
    ],
    keyPoints: 'Flexible models → past: rigid 9-5 hours → technology barriers → today: shorter workweeks → remote software monitoring',
  ),
  ReadingTopicData(
    id: 14,
    title: 'College Welcoming Day',
    sentences: [
      'The day will begin at 10 a.m in the morning with a short presentation.',
      'At the end of this talk, you will meet the heads of departments and teachers.',
      'These staff members will give you a guided tour of our sports facilities.',
      'During this visit, you will need to stay with these students until lunch break.',
      'This meal will be provided on the second floor of the engineering building.',
    ],
    keyPoints: '10 AM presentation → meet department heads & teachers → sports tour → stay with students until lunch → meal at 2nd floor engineering',
  ),
  ReadingTopicData(
    id: 15,
    title: 'End-of-term project',
    sentences: [
      'For end of term project, you need to choose at least 2 of these.',
      'It needs to include relevant images and your own text about the topic.',
      'Then you need to use images and written work to create a presentation.',
      'Your presentation offer your key points and you have 5 minutes to talk.',
      'After this time, other students are able to ask questions and you need to answer them.',
    ],
    keyPoints: 'Choose 2+ items → gather images & text → create presentation → 5 minutes talk → answer student questions',
  ),
  ReadingTopicData(
    id: 16,
    title: 'Company wellness day (Ver 1 - Friday)',
    sentences: [
      'This month, the wellness day took place on Friday, focusing on work-life balance.',
      'More than 50 employees participated, with Mr.A leading a workshop on stress relief.',
      'Activities included team yoga, time management seminars, and a group walk.',
      'Employees enjoyed healthy snacks and exchanged tips for managing stress.',
      'After the workshops, awards were given for the most creative wellness ideas.',
    ],
    keyPoints: 'Friday wellness day → 50+ employees → Mr.A stress relief workshop → yoga & time management → healthy snacks → creative awards',
  ),
  ReadingTopicData(
    id: 17,
    title: 'Company wellness day (Ver 2 - Saturday)',
    sentences: [
      'The wellness fair took place on Saturday afternoon, encouraging healthier lifestyles.',
      'More than 60 participants joined, with Dr. A leading an engaging fitness workshop.',
      'The fair also included cooking demonstrations, mindfulness sessions, and a fun run.',
      'Families enjoyed tasting healthy snacks and discovering tips for better wellness.',
      'After the workshops, prizes were awarded for the most creative health posters.',
    ],
    keyPoints: 'Saturday wellness fair → 60+ participants → Dr. A fitness workshop → cooking & mindfulness → family healthy snacks → poster prizes',
  ),
  ReadingTopicData(
    id: 18,
    title: 'Mae - the math girl (Ver 1 - Family)',
    sentences: [
      'Mae\'s father worked as a nurse, and her mother was a teacher.',
      'Her parents motivated Mae to pursue higher education and scientific studies.',
      'Mae worked diligently and achieved several remarkable milestones.',
      'Eventually, she had the opportunity to undergo a training program in the United States.',
      'She later joined a team, contributing her skills and knowledge.',
    ],
    keyPoints: 'Father: nurse, Mother: teacher → parents motivated → hard work & achievements → USA training program → joined team',
  ),
  ReadingTopicData(
    id: 19,
    title: 'Mae - the math girl (Ver 2 - Space)',
    sentences: [
      'Encouraged by her parents, she decided to study science at university.',
      'Her strong academic record earned her a place in a training program in the USA.',
      'Her passion for space led Mae to join a dedicated research team.',
      'She traveled into space and carried out numerous experiments.',
      'Some experiments involved growing plants and observing animals aboard.',
    ],
    keyPoints: 'Parents encouraged → university science → excellent grades → USA training → space research team → experiments with plants & animals',
  ),
  ReadingTopicData(
    id: 20,
    title: 'Internet of Things (IoT)',
    sentences: [
      'The Internet of Things (IoT) links everyday devices to improve their capabilities.',
      'Early IoT devices faced limitations due to slow internet speeds.',
      'High development costs previously slowed the widespread adoption of IoT.',
      'Nowadays, engineers create smart devices for residential and industrial apps.',
      'Modern IoT systems provide real-time data tracking and automation.',
    ],
    keyPoints: 'IoT connects devices → early: slow internet limits → high costs → modern: smart devices → real-time tracking & automation',
  ),
  ReadingTopicData(
    id: 21,
    title: 'Eating at the restaurant (Salad version)',
    sentences: [
      'I decided to try a new café located at the end of the street.',
      'The place was quite busy, with a lively atmosphere.',
      'Even so, a staff member quickly noticed me and brought over the menu.',
      'I was a bit surprised to see that there were only a few items to choose from.',
      'In the end, I went for the most expensive salad on the menu.',
    ],
    keyPoints: 'New café at street end → busy, lively → staff brought menu → few items → chose expensive salad',
  ),
  ReadingTopicData(
    id: 22,
    title: 'The busy cafe (Sandwich version)',
    sentences: [
      'The café was very crowded when the customer arrived.',
      'The staff helped them find a table and handed them a menu.',
      'The customer was surprised because the menu was different from expected.',
      'They decided to order the most expensive item — a sandwich.',
      'The customer said the sandwich was delicious and would come back again.',
    ],
    keyPoints: 'Crowded café → staff helped find table → menu surprising → expensive sandwich → delicious → will return',
  ),
  ReadingTopicData(
    id: 23,
    title: 'My visit to a new coffee shop (Delicious dish)',
    sentences: [
      'It was my first time visiting a new local coffee shop.',
      'At first, I didn\'t think it would be good, but I decided to give it a try.',
      'I looked at the menu and saw many different kinds of food and drinks.',
      'I chose one dish to try for myself.',
      'When I tasted it, I found it really delicious and knew I would come back.',
    ],
    keyPoints: 'First visit new coffee shop → skeptical but tried → diverse menu → chose one dish → delicious → will return',
  ),
  ReadingTopicData(
    id: 24,
    title: 'Tourism (Online vs Past)',
    sentences: [
      'Modern tourism now provides far more choices than in the past.',
      'In earlier times, travelers mostly depended on guidebooks and paper maps.',
      'Back then, limited technology also meant that booking options were restricted.',
      'Today, online platforms allow people to plan and book their trips with ease.',
      'Local guides now offer personalized tours that give more authentic experiences.',
    ],
    keyPoints: 'Modern: more choices → past: guidebooks & paper maps → limited booking → today: online booking easy → personalized authentic tours',
  ),
  ReadingTopicData(
    id: 25,
    title: 'Work (Open office)',
    sentences: [
      'The company offers flexible working hours to better support employees\' schedules.',
      'Her white desk stands out in the shared open office.',
      'She uses a planner to organize her tasks throughout the shorter workweek.',
      'At lunchtime, she enjoys a homemade sandwich prepared with fresh ingredients.',
      'In the evenings, they unwind by reading books on productivity and well-being.',
    ],
    keyPoints: 'Flexible hours → white desk open office → planner for tasks → homemade lunch sandwich → evening reading on productivity',
  ),
  ReadingTopicData(
    id: 26,
    title: 'A group presentation',
    sentences: [
      'First, we prepared the materials for our group presentation.',
      'Then, we presented our topic for 10 minutes.',
      'Throughout the presentation, we used images to explain our ideas.',
      'After the presentation, other students asked questions.',
      'Finally, each group member took turns answering the questions.',
    ],
    keyPoints: 'Prepare materials → 10 minutes presentation → use images → students ask questions → take turns answering',
  ),
  ReadingTopicData(
    id: 27,
    title: 'Social media evolution',
    sentences: [
      'In the past, slow internet speeds made uploading videos difficult.',
      'Early platforms offered only basic features like text posts.',
      'Over time, social media platforms have greatly evolved in design.',
      'Today\'s platforms use complex algorithms to personalize each user\'s feed.',
      'Many influencers now earn income primarily through brand sponsorships.',
    ],
    keyPoints: 'Past: slow internet → basic text posts → evolved design → complex algorithms for personalization → influencer brand sponsorships',
  ),
  ReadingTopicData(
    id: 28,
    title: 'University open day (ID card)',
    sentences: [
      'Before the open day, contact us so we can record your personal details.',
      'Using this information, we\'ll prepare an ID card for you to collect.',
      'You\'ll need to show this card to enter lectures.',
      'Every visitor will have the chance to join a Q&A session with students.',
      'After the presentations, you\'ll be able to explore different departments.',
    ],
    keyPoints: 'Contact before → prepare ID card → show for entry → Q&A with students → explore departments',
  ),
  ReadingTopicData(
    id: 29,
    title: 'The history of transportation',
    sentences: [
      'In the past, transportation was primarily accessible to the wealthy.',
      'Later, air travel became popular among business professionals.',
      'Eventually, buses and trains were introduced as affordable alternatives.',
      'These made traveling more accessible to everyone.',
      'Today, buses and trains are among the most common transportation options.',
    ],
    keyPoints: 'Past: only wealthy travel → air travel for professionals → buses & trains affordable → everyone can travel → common options today',
  ),
  ReadingTopicData(
    id: 30,
    title: 'Movies (Old vs New)',
    sentences: [
      'Movies today are very different from movies in the past.',
      'In the old days, films were only in black and white, sometimes without sound.',
      'In addition to these technological limits, producers had very low budgets.',
      'Because of the lack of money, actors also earn little money.',
      'Nowadays, actors and producers can earn a lot of money from films.',
    ],
    keyPoints: 'Old films: black & white, no sound → low budget → poor actor earnings → Modern: high earnings from films',
  ),
];
